# Generated by Django 5.2.16 on 2026-07-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Phone number shown on the public profile card.', max_length=32),
        ),
    ]
