# Generated by Django 5.2.16 on 2026-07-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Custom profile banner image.', null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='user',
            name='banner_style',
            field=models.JSONField(blank=True, help_text='Generated banner: {from, to, motifs[]}.', null=True),
        ),
    ]
